apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rails-test
  name: rails-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rails-test
    spec:
      containers:
        - image: gcr.io/dimaz-percobaan/github.com/jerawat12/rails-test
          imagePullPolicy: IfNotPresent
          name: rails-test
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: rails-test
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: rails-test
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rails-test
  name: rails-test-service
  namespace: default
spec:
  clusterIP: 10.3.248.86
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: rails-test
  sessionAffinity: None
  type: ClusterIP

